### ISSUE TITLE
Incorrect link on modal

### ISSUE THREAD

**Issue by grunch** [RGB-Tools/iris-wallet-android#1]
When we touch on a RGB asset transaction to see details the `Change UTXO` link is sending to mempool.space but not exactly to that UTXO.

See image below:

![photo_2022-10-25_14-17-53](https://user-images.githubusercontent.com/228364/197840728-caf55fb0-7944-4a3d-8593-1fcbf975ce49.jpg)

**Comment by nicbus** [comment]
Hi, thanks for reporting this.

The issue has been fixed in the latest released version (0.1.2).
Closing, feel free to re-open if needed.
