### ISSUE TITLE
Avilability on F-Droid

### ISSUE THREAD

**Issue by l29ah** [RGB-Tools/iris-wallet-android#3]
I hope this app will be available in F-Droid, because updating manually is cumbersome, and Google Play isn't FOSS.

https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide

**Comment by fedsten** [comment]
To be available on F-Droid the app would require some changes and it can make the maintenance more time consuming. While it would be nice to have it, currently F-Droid compatibility is not a priority, and it won't probably become one for some time.
