### ISSUE TITLE
App crashing while issuing new token 

### ISSUE THREAD

**Issue by Turtlecute33** [RGB-Tools/iris-wallet-android#4]
Platform: all android versione
Version: 0.1 testnet 

The app crash if you try to issue a token with a number with more than 20 unit (numbers)(for example 10 000 000 000 000 000 000 is fine but  100 000 000 000 000 000 0000 crash),
Would be nice put a UI limit that say: you can't create a token with a higher supply.

**Comment by Cmod777** [comment]
"I'm worried, please fix it" - Von Der Leyen

**Comment by fedsten** [comment]
Fixed 0.1.2, if you try to exceed the max supply the app overrides the your value with the max value `18446744073709551615`
