### ISSUE TITLE
Adding Iris Wallet to our BDK users webpage

### ISSUE THREAD

**Issue by thunderbiscuit** [RGB-Tools/iris-wallet-android#8]
Hi there! I'm thunderbiscuit, I work on the BDK project. We're building a page on our website that includes projects that use BDK, and I'm reaching out to know if you'd be ok with us adding you there! You can take a look at the page on our website here: https://bitcoindevkit.org/case-studies/

Thank you!

**Comment by fedsten** [comment]
Hi thunderbiscuit. Yes absolutely, with pleasure.
